# Generated by Django 5.2 on 2025-05-16 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_Address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.address'),
        ),
    ]
