# Generated by Django 5.2 on 2025-05-16 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100)),
                ('house_number', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=100)),
                ('propDescription', models.TextField()),
                ('propertyType', models.CharField(max_length=100)),
                ('propListingPrice', models.FloatField()),
                ('propListingDate', models.DateField()),
                ('propThumbnail', models.ImageField(blank=True, null=True, upload_to='property/thumbnail')),
                ('propImages', models.ImageField(blank=True, null=True, upload_to='property/images')),
                ('propIsSold', models.BooleanField()),
                ('propBedrooms', models.IntegerField()),
                ('propBathrooms', models.IntegerField()),
                ('propSquareMeters', models.FloatField()),
                ('propAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.address')),
                ('sellerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.seller')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSubmitted', models.DateField(auto_now_add=True)),
                ('dateExpires', models.DateField()),
                ('offerPrice', models.FloatField()),
                ('offerStatus', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Contingent', 'Contingent')], default='Pending', max_length=20)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_offers', to=settings.AUTH_USER_MODEL)),
                ('propertyId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property')),
                ('sellerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.seller')),
            ],
        ),
        migrations.CreateModel(
            name='FinalizedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, null=True)),
                ('nationalId', models.IntegerField()),
                ('paymentMethod', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Mortgage', 'Mortgage')], max_length=20)),
                ('paymentDetails', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.address')),
                ('offerId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.purchaseoffer')),
            ],
        ),
    ]
