# Generated by Django 5.2 on 2025-05-16 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100)),
                ('house_number', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=100)),
                ('propDescription', models.TextField()),
                ('propertyType', models.CharField(max_length=100)),
                ('propListingPrice', models.FloatField()),
                ('propListingDate', models.DateField()),
                ('propThumbnail', models.ImageField(blank=True, null=True, upload_to='property/thumbnail')),
                ('propImages', models.ImageField(blank=True, null=True, upload_to='property/images')),
                ('propIsSold', models.BooleanField()),
                ('propBedrooms', models.IntegerField()),
                ('propBathrooms', models.IntegerField()),
                ('propSquareMeters', models.FloatField()),
                ('propAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.address')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
