# Generated by Django 5.2 on 2025-05-08 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='propertyId',
        ),
        migrations.AddField(
            model_name='property',
            name='sellerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.seller'),
        ),
        migrations.AlterField(
            model_name='property',
            name='propImages',
            field=models.ImageField(blank=True, null=True, upload_to='property/images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='propThumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='property/thumbnail'),
        ),
    ]
