# Generated by Django 5.2 on 2025-05-16 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AddField(
            model_name='property',
            name='built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sellerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.seller'),
        ),
        migrations.CreateModel(
            name='PurchaseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSubmitted', models.DateField(auto_now_add=True)),
                ('dateExpires', models.DateField()),
                ('offerPrice', models.FloatField()),
                ('offerStatus', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Contingent', 'Contingent')], default='Pending', max_length=20)),
                ('buyerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.buyer')),
                ('propertyId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property')),
                ('sellerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.seller')),
            ],
        ),
        migrations.CreateModel(
            name='FinalizedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, null=True)),
                ('nationalId', models.IntegerField()),
                ('paymentMethod', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Mortgage', 'Mortgage')], max_length=20)),
                ('paymentDetails', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.address')),
                ('offerId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.purchaseoffer')),
            ],
        ),
    ]
