# Generated by Django 5.2 on 2025-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_address_options_property_built_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizedoffer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
