# Generated by Django 5.2 on 2025-05-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_propertyid_property_sellerid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
