# Generated by Django 5.2 on 2025-05-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_property_propimages_propertyimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimages',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
