# Generated by Django 5.2 on 2025-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_propertyimages_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='postalCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
